sudo: required
dist: trusty
language: python
notifications:
  email:
    recipients:
    - lorena.pantano@gmail.com
    on_failure: always
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
- bash Miniconda-latest-Linux-x86_64.sh -b -p ~/install
install:
- export PATH=~/install/bin/:$PATH
- conda install --yes ncurses -c conda-forge
- conda install --yes -c bioconda bedtools samtools pip nose pysam pandas pyyaml pybedtools  biopython setuptools -q 
  # - conda install --yes -c bioconda htslib=1.3
script:
- python setup.py develop
- nosetests
branches:
  only:
  - master
  - dev
deploy:
  provider: pypi
  user: lpantano
  password:
    secure: cxfwBMREy+KIQl7Y2EeT8fBChASr6F7GvZxkwe7xXhwPS5Ezw51IX5ktHz8s8O6psseSP6GFLOzfc6wUTY2KM9i5syFtQUc8dQ8B4GmPbZKb+r8hcu4Q3VQqyrkMgyOV6DZ3jZ/Dowqd0005c5tW872RB3ABjflEq1xOr3ddOAp1UmjswYoM+cHE6gurT3z7XYyWS8O6jBee27Pf/tZkrc5tQaN6uVyEvEbYgtkomJ46CsKhgXACqQJiW6CKbzc03VypjEs+oUDNu6DsXmTuTXRyDHH/CA9M0zmQc9EOfZuBauwJ7/PgAS7LVICTq9cvq5RZ4sGEdZ1I1FDTMupp4Hybt6kbEU+Pntfj0nWWYhRZkeWN96Gar7p2BEQ9y68zVvyoM3S3fshLCYF1gonI4Dvy2XXjy+zyQuOSiNbqKwR/GjeDZV/U/TVhIVakQ7yQllyv2Fio8pwE28qpgfIhaddRC+Cp2KBhFBbpwM8Mxx5PeayTIQnhD3zDUt8ZdP1djvH4q/S+qLp77l2znD9CwaELYEzXvVbocsyed4jsXbMtD1z092JViA9/YzZPnuQ0PR7Ccs1bsdvMI0gOyoIroTEP+aPkXKyrL5O7O3sF8UX0ES0vxOC9cJwpEPH39sRxYxjJ4K1NpaGWlHiZG0hihLP6QkeBDthMYNEb0Veqcwc=
  on:
    branch: master
    branch: dev
    distributions: sdist bdist_wheel
    repo: miRTop/mirtop
